### ISSUE TITLE
Envforcer seems like a much cooler name

### ISSUE THREAD

**Issue by cpjolicoeur** [mojotech/env-enforcer#11]
just saying :smile:

**Comment by joelhawksley** [comment]
Already taken: https://github.com/nathanleiby/envforcer

**Comment by cpjolicoeur** [comment]
gaaaaah.

wait, so what.  that is Go, this is Ruby.

https://dl.dropboxusercontent.com/spa/5649sdttrqrua6c/flfr-lcv.png

**Comment by joelhawksley** [comment]
you're right. let's do it.

**Comment by joelhawksley** [comment]
Done.
